name: Deploy to IPFS via Pinata (manual)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip website folder
        run: |
          zip -r website.zip . -x ".git/*"

      - name: Upload to Pinata via API
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
        run: |
          curl -X POST https://api.pinata.cloud/pinning/pinFileToIPFS \
            -H "pinata_api_key: $PINATA_API_KEY" \
            -H "pinata_secret_api_key: $PINATA_SECRET_API_KEY" \
            -F "file=@website.zip" \
            -F "pinataMetadata={\"name\": \"github-site-deploy\"};type=application/json"
